apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bookshop-web
  template:
    metadata:
      labels:
        component: bookshop-web
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
        volumeMounts:
        - name: settings
          mountPath: /etc/bookshop
      volumes:
      - name: settings
        configMap:
          name: bookshop-config
