apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalog
  template:
    metadata:
      labels:
        component: catalog
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
