apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: inventory-api
  template:
    metadata:
      labels:
        component: inventory-api
    spec:
      containers:
      - name: app
        image: busybox:1.36
        command: ["sh", "-c", "echo db at $DB_HOST; sleep 3600"]
        env:
        - name: DB_HOST
          value: set-by-kustomize
