#!/usr/bin/env python3
"""Regenerate workbook.md from drill.md, and optionally render both to HTML.

    python3 drills/build.py           # workbook.md only
    python3 drills/build.py --html    # also drill.html + workbook.html (needs `pip install markdown`)

workbook.md is the drill deck with the answers stripped out: every numbered
question from drill.md, followed by an empty code fence to write your answer in.
Don't edit it by hand; edit drill.md and rerun this script.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
DRILL = HERE / "drill.md"
WORKBOOK = HERE / "workbook.md"

SECTION = re.compile(r"^## (\d+)\. (.+)$")
QUESTION = re.compile(r"^### (\d+\.\d+) (.+?)(?: — \[[^\]]+\]\([^)]+\))?\s*$")

WORKBOOK_HEADER = """# CKAD Workbook

> A blank copy of [drill.md](drill.md): same questions, same numbering, no answers.
> Write your answer in the empty block under each question, then check it against drill.md.
> Mark the ones you got wrong or hesitated on with an `x` and redo them next session.
>
> Generated by `python3 drills/build.py` — edit drill.md, not this file.

---
"""


def build_workbook() -> None:
    out = [WORKBOOK_HEADER]
    in_fence = False
    for line in DRILL.read_text(encoding="utf-8").splitlines():
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if m := SECTION.match(line):
            out.append(f"\n## {m.group(1)}. {m.group(2)}\n")
        elif m := QUESTION.match(line):
            out.append(f"### {m.group(1)} {m.group(2)}\n\n```bash\n\n```\n")
    WORKBOOK.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {WORKBOOK.relative_to(HERE.parent)}")


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>{title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body {{ font-family: sans-serif; max-width: 900px; margin: 40px auto; padding: 0 16px; line-height: 1.6; color: #222; }}
  h1, h2, h3 {{ border-bottom: 1px solid #ddd; padding-bottom: 4px; }}
  code {{ background: #f4f4f4; padding: 2px 5px; border-radius: 3px; font-size: 0.9em; }}
  pre {{ background: #f4f4f4; padding: 12px; border-radius: 5px; overflow-x: auto; }}
  pre code {{ background: none; padding: 0; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 12px; text-align: left; }}
  blockquote {{ border-left: 4px solid #ddd; margin: 0; padding-left: 12px; color: #666; }}
  details {{ margin: 8px 0 16px; }}
  summary {{ cursor: pointer; color: #0066cc; }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def build_html() -> None:
    try:
        import markdown
    except ImportError:
        sys.exit("--html needs the markdown package: pip install markdown")
    for src in (DRILL, WORKBOOK):
        body = markdown.markdown(
            src.read_text(encoding="utf-8"),
            extensions=["tables", "fenced_code", "toc", "md_in_html"],
        )
        dst = src.with_suffix(".html")
        dst.write_text(HTML_TEMPLATE.format(title=src.stem, body=body), encoding="utf-8")
        print(f"wrote {dst.relative_to(HERE.parent)}")


if __name__ == "__main__":
    build_workbook()
    if "--html" in sys.argv[1:]:
        build_html()
