apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartdate-2
spec:
  startingDeadlineSeconds: 30
  jobTemplate:
    metadata:
      name: heartdate-2
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - image: busybox
            name: heartdate
            resources: {}
            command: ["sh", "-c", "date"]
          restartPolicy: OnFailure
  schedule: "* * * * *"
