apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      component: storefront
  template:
    metadata:
      labels:
        component: storefront
    spec:
      containers:
      - name: app
        image: nginx
