apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      component: recommendations
  template:
    metadata:
      labels:
        component: recommendations
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
