apiVersion: v1
kind: Pod
metadata:
  name: volume-configmap-pod
spec:
  containers:
  - image: nginx
    name: nginx
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: vol-config
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: vol-config
    configMap:
      name: app-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
