apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-secretmap
  name: test-secretmap
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: DB_PASSWORD     # env var name can differ from the Secret key
      valueFrom:
        secretKeyRef:
          name: orders-db-login
          key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Never
