apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bob-db
  labels:
    app: bob-db
spec:
  selector:
    matchLabels:
      app: bob-db
  serviceName: bob-db
  replicas: 3
  template:
    metadata:
      labels:
        app: bob-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
